services:
  - type: web
    name: fams-backend
    env: python
    rootDir: backend
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        sync: false
      - key: KFMS_JWT_SECRET
        generateValue: true
      - key: KFMS_ALLOWED_ORIGINS
        sync: false
